apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    {{- include "codeanker.label" . | indent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
        {{- include "codeanker.label" . | indent 8 }}
      # annotations:
      #   vault.hashicorp.com/agent-inject: "true"
      #   vault.hashicorp.com/agent-inject-secret-env: "database/creds/k8s-staging-{{ .Chart.Name }}"
      #   vault.hashicorp.com/agent-inject-template-env: |
      #     {{`{{- with secret "database/creds/k8s-staging-`}}{{ .Chart.Name }}{{`" -}}
      #     MONGODB=mongodb://praecura:ephJ+oLf2ww=@mongodb.k8s-staging-mongodb.svc.cluster.local:27017/k8s-staging-`}}{{ .Chart.Name }}{{`?authSource=admin
      #     {{- end }}`}}
      #   vault.hashicorp.com/role: "k8s-staging-{{ .Chart.Name }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: codeanker/{{ .Chart.Name }}-api:{{ .Values.global.commit }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
      imagePullSecrets:
        - name: codeanker-docker-key
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api-svc
  labels:
    app: {{ .Chart.Name }}-api
    {{- include "codeanker.label" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ .Chart.Name }}-api
